### ISSUE TITLE
Criar issues no github

### ISSUE THREAD

**Issue by intrepidocabral** [lafabbricabr/mapasculturaisThemeHortas#1]
Seguir o seguinte documento orientador para a construção das issues:

[2016_10_28_mapasculturais_sistema_de_hortas.pdf](https://github.com/institutotim/mapasculturaisThemeHortas/files/536515/2016_10_28_mapasculturais_sistema_de_hortas.pdf)

**Comment by thaisrigolon** [comment]
Não consegui abrir o documento, está off... page not found.

**Comment by intrepidocabral** [comment]
Segue novamente: [2016_10_28_mapasculturais_sistema_de_hortas.pdf](https://github.com/robertkapa/mapasculturaisThemeHortas/files/569530/2016_10_28_mapasculturais_sistema_de_hortas.pdf)
