### ISSUE TITLE
Filtros

### ISSUE THREAD

**Issue by thaisrigolon** [lafabbricabr/mapasculturaisThemeHortas#13]
# Entidade Escola

- **Filtros Principais e na home:** 
- [x]  DRE
- [x]  Tipo de escola
- [x]  Escolas com horta e Ass. Técnica

- **Filtros da lateral:** 
- [x] A escola tem acesso permanente a insumos consumíveis para horta?
- [x] A escola faz compostagem?
- [x] A escola conta com coleta seletiva na porta?
- [x] A escola faz separação de resíduos sólidos?
- [x] É uma escola de educação integral? 
- [x] A escola realiza captação de água da chuva 
- [x] A escola tem ferramentas disponíveis para horta na escola?
- [x] É uma horta com objetivo pedagógico?
- [x] Quais são os tipos de cultivo utilizados?
- [x] A escola tem uma ou mais árvores frutíferas?
- [x] Estas árvores frutíferas são utilizadas com objetivo pedagógico?
- [x] A escolas tem viveiro?
- [x] Quais são os tipos e quantidades de ferramentas disponíveis para horta na escola?
- [x] Quais são os tipos de alimentos cultivados? 
- [x] Qual a quantidade de alunos envolvidos com horta?
- [x] A escola conta com assistência técnica para compostagem? 
- [x] Qual a quantidade de  alunos envolvidos com compostagem?

# Entidade Agentes

Tirar o filtro de área.

**Comment by GustavoVS** [comment]
Perguntas aparentemente duplicadas:
- A escola tem ferramentas disponíveis para horta na escola?
- Quais são os tipos e quantidades de ferramentas disponíveis para horta na escola?

Considerada a primeira (A escola tem ferramentas disponíveis para horta na escola?)

**Comment by thaisrigolon** [comment]
Hun, entendi o seu ponto, mas a resposta das duas perguntas são diferentes, mesmo que pareça ser duplicado. O que você sugere, manter apenas a primeira?

**Comment by thaisrigolon** [comment]
Quando tento rolar a página para ver todos os filtros avançados não consigo. A barra de rolagem não deixa:

![1](https://cloud.githubusercontent.com/assets/18294515/21095629/807c63fe-c043-11e6-9372-d29f270e98ba.png)
