### ISSUE TITLE
Nomenclatura da planilha de dados exportados

### ISSUE THREAD

**Issue by thaisrigolon** [lafabbricabr/mapasculturaisThemeHortas#16]
Quando os dados dos agentes e das escolas são exportados, a planilha vem nomeada como Mapas Culturais. Alterar a nomenclatura para Gestão de Hortas.

**Comment by GustavoVS** [comment]
Atualmente no branch  https://github.com/institutotim/mapasculturais/tree/config_excelname

Necessário aprovar pro 'core' do mapas os seguintes pull requests

https://github.com/hacklabr/mapasculturais/pull/1002/files
https://github.com/hacklabr/mapasculturais/pull/1003/files
https://github.com/hacklabr/mapasculturais/pull/1004/files

**Comment by thaisrigolon** [comment]
Entendi. Tudo bem é prioridade baixar, mas já vi que você enviou os PR`s para o Hacklab aprovar.
Obrigada :)
