### ISSUE TITLE
Customização da entidade Espaço

### ISSUE THREAD

**Issue by intrepidocabral** [lafabbricabr/mapasculturaisThemeHortas#2]
> ATENÇÃO: caso haja dúvidas, ver documentação aqui #1 
- [x] A entidade espaços deve ser renomeada para ESCOLAS;
- [x] A entidade deve conter novos campos no cadastro (foi dado destaque aqui em negrito para campos diferenciados), que serão divididos em 4 dimensões: 
  Institucional, Cultivo, Compostagem e Coleta Seletiva. Exemplo:

![mapasculturais-hortas_escolas](https://cloud.githubusercontent.com/assets/641411/19483848/8156623c-9534-11e6-82da-528725adc2fd.png)
# Dimensão Institucional
- [ ] Os campos da dimensão INSTITUCIONAL são:
- **Nome da escola**:
- **Endereço da escola (manter os campos já presentes na entidade espaço)**:
- **Localização: (Latitude, Longitude - manter os campos já presentes na entidade espaço)**:
- **Telefone da escola**:
- **Email da escola**:
- **Número INEP** (8 dígitos):
- **Código EOL**  (12 dígitos):
- **DRE a qual está vinculada** (type: Dropdown - 13 itens):
  - DRE Butantã
  - DRE Campo Limpo
  - DRE Capela do Socorro
  - DRE Freguesia/Brasilândia
  - DRE Guaianases
  - DRE Ipiranga
  - DRE Itaquera
  - DRE Jaçanã/Tremembé
  - DRE Penha
  - DRE Pirituba Jaraguá
  - DRE Santo Amaro
  - DRE São Mateus
  - DRE São Miguel
- **Tipo de Escola** (type: checkbox multi choice);
  - CCI/CIPS
  - CECI
  - CEI Direta
  - CEI Indireta
  - CEU CEI
  - CEU EMEI
  - Creche Conveniada
  - EMEI
  - CEMEI
  - EMEBS Infantil
  - EMEF
  - CEU EMEF
  - EMEBS EMEF
  - EJA Regular
  - EJS Modular
  - CIEJA
  - MOVA
  - Ensino Médio Regular
  - Ensino Profissionalizante
- **Número de alunos matriculados** (type: numeric):
- **Nome do Diretor**:
- **Email do Diretor**:
- **Nome do Coordenador Pedagógico**:
- **Email do Coordenador Pedagógico**:
- **Projeto Político Pedagógico** (type: upload file): 
- **Projetos em andamento** (type: upload file):
- **Galeria de Imagens**:
- **É uma escola de educação integral?** (radio button or dropdown);
  - Não
  - Integral (até 35h semanais ou mais)
  - Parcial (até 34,5h semanais)

# Dimensão Cultivo
- [ ] Os campos da dimensão CULTIVO são:
- **A escola tem horta?**:
  - Sim
  - Não
- **É uma horta com objetivo pedagógico?**:
  - Sim
  - Não
- **Quais são os tipos de cultivo utilizados?**:
  - Cultivo acima do solo
  - Cultivo no solo
  - Cultivos verticais 
  - Cultivo em telhados
- **A escola tem uma ou mais árvores frutíferas?**:
  - Sim
  - Não
- **Estas árvores frutíferas são utilizadas com objetivo pedagógico?**:
  - Sim
  - Não
- **A escola tem viveiro?**:
  - Sim
  - Não
- **A escola conta com assistência técnica permanente para horta, pomar ou viveiro?** Opções (radio button one choice or dropdown):
  - Não
  - Técnico da SME
  - Técnico da SVMA
  - Técnico da SDTE
  - Técnico da SMS
  - Técnico de ONG
  - Técnico da comunidade Escolar
  - Outros
- **A escola realiza captação de água da chuva?**:
  - Sim
  - Não
- **Nome de um ou mais envolvidos com atividades na horta, pomar ou viveiro**:
- **Email de um ou mais envolvidos com atividades na horta, pomar ou viveiro**:
- **A escola tem acesso permanente a insumos consumíveis para horta?** (type: checkbox multi choice);
  - Calcário
  - Adubo
  - Orgânico
  - Terra
  - Palha
  - Composto
  - Sementes
  - Mudas
  - Biofertilizante
  - Triturado de poda
  - Manta bidimensional
  - Argila expandida
  - Pedrisco
  - Sacho
- **Quais são os tipos e quantidades de ferramentas disponíveis para horta na escola?** (type: checkbox multi choice);
  - Enxadão estreito
  - Enxada padolfo larga
  - Ancinho
  - Rastelo
  - Pazinha de mão
  - Cavadeira
  - Pá quadrada
  - Pá de bico
  - Peneira de areia
  - Pá quadrada
  - Tesoura de poda
  - Mangueira
  - Regador
  - Balde
  - Luvas
- **Qual é a área cultivada em m2?** (type: numeric):
- **Qual a área cultivável em m2?** (type: numeric):
- **Quais são os tipos de alimentos cultivados?** (type: checkbox multi choice);
  - Frutas
  - Verduras
  - Legumes
  - Leguminosas
  - Temperos
  - Medicinais
  - PANCs
- **Qual a quantidade de alunos envolvidos com horta?** (type: numeric):

# Dimensão Compostagem
- [ ] Os campos da dimensão COMPOSTAGEM são:

- **A escola faz compostagem?**:
  - Não
  - Sim, com minhocário
  - Sim, com composteira termofílica
- **Nome de um ou mais envolvidos com atividades de compostagem**:
- **Email de um ou mais envolvidos com atividades de compostagem**:
- **Qual a quantidade de alunos envolvidos com compostagem?** (type: numeric):
- **A escola conta com assistência técnica para compostagem?**:
  - Sim
  - Não

# Dimensão Coleta Seletiva
- [ ] Os campos da dimensão COLETA SELETIVA são:
- **A escola conta com coleta seletiva na porta?**:
  - Não
  - Caminhão de coleta seletiva da prefeitura
  - Cooperativa de coleta credenciada pela prefeitura
  - Outros
- **A escola faz separação de resíduos sólidos?**:
  - Sim
  - Não
- **Nome do responsável pela separação de resíduos para coleta seletiva**:
  - Não
  - Caminhão de coleta seletiva da prefeitura
  - Cooperativa de coleta credenciada pela prefeitura
  - Outros
- **Nome do responsável pela separação de resíduos para coleta seletiva**:
- **Email do responsável**:

**Comment by GustavoVS** [comment]
Resolvida em pedaços menores em:

https://github.com/lafabbricabr/mapasculturaisThemeHortas/issues/7
https://github.com/lafabbricabr/mapasculturaisThemeHortas/issues/8
https://github.com/lafabbricabr/mapasculturaisThemeHortas/issues/9
