### ISSUE TITLE
Inserção de dados na base

### ISSUE THREAD

**Issue by intrepidocabral** [lafabbricabr/mapasculturaisThemeHortas#3]
A partir de uma planilha com os dados das escolas, inserir na base de dados antes do lançamento;

Tarefas: 
- [x] Preparar planilha conforme modelo de entidade atual. Veja modelo de planilha: 

[2016_11_mapas_culturais_exemplo.xlsx](https://github.com/robertkapa/mapasculturaisThemeHortas/files/569593/2016_11_mapas_culturais_exemplo.xlsx)

- [x] Enviar planilha ao responsável;
- [x] Receber dados de planilha;
- [x] Realizar insert na base de dados;

**Comment by thaisrigolon** [comment]
O modelo da planilha está fora do ar... page not found.

**Comment by intrepidocabral** [comment]
update na planilha!
